name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 또는 배포하고자 하는 브랜치 이름

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build project
      run: |
        cd client
        npm install
        npm run build

    - name: Create .nojekyll file
      run: |
        touch ./docs/.nojekyll

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        publish_branch: gh-pages
        cname: ''
